[[redirects]]
from = "/api/"
to = "https://calendar-backend-8gf9.onrender.com:/splat"
status = 200
force = true
headers = {X-From = "Netlify"}
[[headers]]
for = "/"
[headers.values]
Access-Control-Allow-Origin = "*"